language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t artburlaka/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true artburlaka/react-test npm test
  
after_success:
  - docker build -t artburlaka/multi-client ./client
  - docker build -t artburlaka/multi-nginx ./nginx
  - docker build -t artburlaka/multi-server ./server
  - docker build -t artburlaka/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push artburlaka/multi-client
  - docker push artburlaka/multi-nginx
  - docker push artburlaka/multi-server
  - docker push artburlaka/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-711637092958
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
